### PR TITLE
Support generic HTTP auth with opendap

### PR DESCRIPTION
**Pull request by leifdenby**
intake-xarray currently can only authenticate against the OPeNDAP servers provided in https://github.com/pydap/pydap/tree/master/src/pydap/cas. This commit adds an `auth` option called `generic_http` for the OPeNDAP driver,
following the directions at http://xarray.pydata.org/en/stable/io.html#opendap

### CODE REVIEW

**Comment by martindurant** [comment]
Looks OK to me, although I am no DAP expert - would love a comment from someone who is.
Given that this is HTTP only, is it plausible to test directly?

**Comment by martindurant** [comment]
Also, help appreciated with this likely unrelated error
```
  File "/home/travis/build/intake/intake-xarray/intake_xarray/netcdf.py", line 57, in __init__
    super(NetCDFSource, self).__init__(metadata=metadata, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'engine'
```

**Comment by d70-t** [comment]
@martindurant / unrelated engine error: `git bisect` says [this one](https://github.com/intake/intake/commit/08412c6b679469ef67ca25fd91105410fab3d76d) broke it.

**Comment by d70-t** [comment]
... and the `engine` refers to [this location](https://github.com/intake/intake-xarray/blob/master/intake_xarray/tests/data/catalog.yaml#L16), however I did not validate if other tests fail if that line is commented out.

**Comment by martindurant** [comment]
Yeah, it looks like it should be 
```
      xarray_kwargs:
        engine: pynio
```
but why did this work before?

**Comment by martindurant** [comment]
(perhaps all that happened, is that this entry was never tested, because the backend wasn't installed, and the change in Entry to instantiate the source object revealed the previous bug in the catalog)

**Comment by d70-t** [comment]
I am pretty new to intake, so I can't really judge this. But I could not find a way how `engine` would have made it to the xarray `open_dataset` call before. By applying your change I'd understand how the parameter would make its way through.

**Comment by martindurant** [comment]
@leifdenby , do you have time to implement the fix in this PR?

**Comment by d70-t** [comment]
I'd propose to handle it in a separate PR #75 as this seems to be a separate issue.

**Comment by martindurant** [comment]
OK, so this PR needs to merge from master

**Comment by weiji14** [comment]
Haven't tried this branch (authentication is hard to test!) , but the new 'generic_http' auth method should be added to the docstring here:

https://github.com/intake/intake-xarray/blob/97c869ec99fd50b1f06a5c2e5daaf10f07c3afae/intake_xarray/opendap.py#L29-L36

**Comment by leifdenby** [comment]
@martindurant and @d70-t I can wait until a fix has been merged for the CI tests. Maybe that is best?

thanks @weiji14 I've updated the docstring

**Comment by d70-t** [comment]
@leifdenby I think that @martindurant suggested that you would merge the current master (which already has the CI fix) into you branch. But maybe github was also clever enough to run the latest PR checks on what would be the result of merging this PR into master, which would essentially result in the same state of the working directory. Anyways, I think this PR should be fine for now.
